<?php return array(

// texte uniquement (sans balises)
"metaCanonical"	 	  => "http://www.credit-conseil.ch/en/benefits/data-protection.html",
"metaRobots"		    => "index,follow",
"metaDescription"	  => "Data protection",
"metaTitle"			    => "Privacy - Data Protection: CC Crédits Conseils SA",


// inclu les balises (p.ex <script> ou <link>)
"header_debut"	            => "",
"header_fin"		            => "",
"javascript_debut"	        => "",
"javascript_avant_default"	=> "",
"javascript_fin"	          => "",

"background"		=> "/ressources/unilang/avantages/banner_avantages_protectdata.jpg",

"documentsARemettre" => "oui",
"calculateurBudget" => "oui",
"demandeCourrier" 	=> "oui",
"avantages" 		=> "non",
"avantagesListe"	=> "
	<li>Avantage 1</li>
	<li>Avantage 2</li>
	<li>Avantage 3</li>
	<li>Avantage 4</li>
	<li>Avantage 5</li>
	<li>Avantage 6</li>
	<li>Avantage 7</li>
",

"titrePage"			=> "Privacy - data protection",

"zone1"				=> "
<h2>Collection and processing of your personal data</h2>
<p>CC Crédits Conseils SA commits to respect your data as per the current legislation on data protection.</p>

<p>Every data entered or transmitted through the application form or the contact form will only be used in order to respond to a credit application or information. It is the same for the data that CC Crédits Conseils SA may read, as the supporting documents sent to build your credit file.
</p> 

<p>Your data can also be used as part of an implementation of internal statistics. In the event we would like to use your data for other purposes, this would only be possible after obtaining your prior consent. 
</p>

<h2>Passing on of your personal data to a third</h2>
<p>Your data are treated confidentially and we won’t share or sell them to third parties.<br/>
However, so that we give you a reply to your credit application and obtain offers tailored to your situation, we transmit the essential information to our financial partners. They are required to use your data exclusively in the service of their functions and agree never to communicate, disclose or share your data.</p>

<p>
	Unless required by the law, your data are disclosed to any third party and in any other case. 
<p/>

<h2>Application form: Security of the transmitted data</h2>

<p>To protect your data, we use technological means to meet the safety standards: when sending the credit application form to our database, the entered data are encrypted by SSL transmission process.<br/>
Your data are then processed by computer and stored in a secure environment at our service provider.<br>
Every person with access to your personal data formally commits to this privacy policy and not disclose, divulge or share your personal data.</p>

<h2>Access and correction right of your data</h2>
<p>CAccording to the Federal Law on the Data Protection in the RS 235.1 of 19th June 1992, you have the right to access, rectify and suppression data concern you.  
<br><br>
If you wish to exert this right, you just have to apply by mail at the following address: <br>
CC Crédits Conseils SA<br>
Av. de Choiseul 23-25<br>
CP 100<br>
1290 Versoix<br>
<br>
The procedure is the same if you created an account on our website and want to close it.</p>

<h2>Use of cookies</h2>
<p>Our site turns to the use of cookies. These text files stored on your hard drive does not contain any personal information about you, but can allow identifying you during your next visit so that we offer you a personalized service.<br>
This site also uses Google Analytics, a monitoring service of website provided by Google Inc. (“Google”). Google Analytics also uses cookies to allow an analysis of the use made of the site by its users. Google will use the information from cookies in the aim to evaluate your use of the site and the way you login, compile reports on the website activity on our request and provide other services relating to the website activity and the use of internet. These data are completely anonymous. They will be used to improve the content of our website and our services.<br>
The data generated by the cookies about your use of the website (including your IP address) will be transmitted and stored by Google on servers in the United States. Google may also transfer this information to third parties when required by law or when such third parties process these data on Google’s behalf, including the site editor.<br>
Google won’t associate you IP address with any other data held by Google. By using this website, you consent to the processing of your nominative data by Google in the here above conditions and for the purposes just described. 
</p>

<h2>External links</h2>
<p>The external links in place as part of this site and the contents of their sites are not the responsibility of Crédits Conseils SA.<br>
Our site may unwittingly have been linked to other website through links: we are not responsible for the information presented on these other sites.</p>

",

"end"=>""



// 
// <div class="column col100 rightCol leftCol"></div>
// <div class="column col50 leftCol"></div>
// <div class="column col50 rightCol"></div>
// 

);?>
